version: "3.8"

services:
  merge-solver-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "merge-solver-api"
    environment:
      - PROD=true
    ports:
      - "8090:8090"
    env_file:
      - .env
